use_frameworks!

platform :ios, '11.0'

target 'AudioQueueMananger_Example' do
  pod 'AudioQueueMananger', :path => '../'

  target 'AudioQueueMananger_Tests' do
    inherit! :search_paths

    
  end
end
